# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.234
loader_version_range=[1,)


mod_id=insanesurvivaloverhaul
modrinth_slug=iguanatweaks-reborn
mod_group_id=insane96mcp.insanesurvivaloverhaul
mod_name=Insane's Survival Overhaul
mod_license=All Rights Reserved
mod_version=5.11.2.0-beta

insanelib_version=2.4.28.0
insanelib_version_range=[2.4.28.0,)

emi_version=1.1.24